name: Robot Framework CI

on:
  push:
    branches:
      - master, WIP
  pull_request:
    branches:
      - master

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'BUILD_DEMO'
          project-name: 'DEMO'
      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      - name: 'Building the framework'
        run: pip install -r requirements.txt
      - name: 'Execute Tests'
        run: browserstack-sdk robot -d output ./testScripts/uiTestCases/FindNewCarsTest_DataDriven.robot
      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
      - name: Run Robot Framework tests and generate report
        run: |
            echo "ROBOT_RC=$?" >> "$GITHUB_ENV"
        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
        #   if: env.ROBOT_RC != '0'
        #   run: |
        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
        #     exit 1
      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: output